-- RedThunder Combo Catalogue
-- Safe additive schema: does not modify products, orders, cart, auth, RLS on existing tables, RPCs, storage, or edge functions.
-- Architecture: one normalized master table + one normalized detail table.
-- Do NOT create one physical table per combo; each combo is an independent master record with its own item rows.

create table if not exists public.combo_packs (
  id uuid primary key default gen_random_uuid(),
  website_key text not null default 'cart' check (website_key = 'cart'),
  combo_code text not null,
  name text not null,
  slug text not null,
  short_title text,
  description text,
  tagline text,
  image_url text,
  budget_tier text check (budget_tier is null or budget_tier in ('STARTER','FAMILY','FESTIVAL','PREMIUM','GRAND')),
  pricing_mode text not null default 'LIVE_SUM' check (pricing_mode in ('LIVE_SUM','MANUAL')),
  manual_price numeric(12,2) check (manual_price is null or manual_price >= 0),
  badge_text text,
  is_active boolean not null default true,
  is_featured boolean not null default false,
  display_order integer not null default 0 check (display_order >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (website_key, combo_code),
  unique (website_key, slug)
);

create table if not exists public.combo_pack_items (
  id bigint generated by default as identity primary key,
  combo_id uuid not null references public.combo_packs(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  display_order integer not null default 0 check (display_order >= 0),
  item_label text,
  item_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (combo_id, product_id)
);

create index if not exists combo_packs_active_order_idx
  on public.combo_packs (website_key, is_active, display_order, id);
create index if not exists combo_pack_items_combo_order_idx
  on public.combo_pack_items (combo_id, display_order, id);
create index if not exists combo_pack_items_product_idx
  on public.combo_pack_items (product_id);

alter table public.combo_packs enable row level security;
alter table public.combo_pack_items enable row level security;

revoke all on public.combo_packs from anon, authenticated;
revoke all on public.combo_pack_items from anon, authenticated;
grant select on public.combo_packs to anon, authenticated;
grant select on public.combo_pack_items to anon, authenticated;
grant insert, update, delete on public.combo_packs to authenticated;
grant insert, update, delete on public.combo_pack_items to authenticated;

drop policy if exists combo_packs_public_read on public.combo_packs;
create policy combo_packs_public_read
  on public.combo_packs for select
  to anon, authenticated
  using (website_key = 'cart' and is_active = true);

drop policy if exists combo_packs_admin_write on public.combo_packs;
create policy combo_packs_admin_write
  on public.combo_packs for all
  to authenticated
  using ((select private.is_admin()) and website_key = 'cart')
  with check ((select private.is_admin()) and website_key = 'cart');

drop policy if exists combo_pack_items_public_read on public.combo_pack_items;
create policy combo_pack_items_public_read
  on public.combo_pack_items for select
  to anon, authenticated
  using (
    exists (
      select 1 from public.combo_packs c
      where c.id = combo_pack_items.combo_id
        and c.website_key = 'cart'
        and c.is_active = true
    )
  );

drop policy if exists combo_pack_items_admin_write on public.combo_pack_items;
create policy combo_pack_items_admin_write
  on public.combo_pack_items for all
  to authenticated
  using (
    (select private.is_admin()) and exists (
      select 1 from public.combo_packs c
      where c.id = combo_pack_items.combo_id and c.website_key = 'cart'
    )
  )
  with check (
    (select private.is_admin()) and exists (
      select 1 from public.combo_packs c
      where c.id = combo_pack_items.combo_id and c.website_key = 'cart'
    )
  );

create or replace function public.set_combo_updated_at()
returns trigger language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists combo_packs_set_updated_at on public.combo_packs;
create trigger combo_packs_set_updated_at
before update on public.combo_packs
for each row execute function public.set_combo_updated_at();

drop trigger if exists combo_pack_items_set_updated_at on public.combo_pack_items;
create trigger combo_pack_items_set_updated_at
before update on public.combo_pack_items
for each row execute function public.set_combo_updated_at();

create or replace view public.combo_pack_catalogue as
select
  c.id, c.website_key, c.combo_code, c.name, c.slug, c.short_title, c.description, c.tagline,
  c.image_url, c.budget_tier, c.pricing_mode, c.manual_price, c.badge_text, c.is_active,
  c.is_featured, c.display_order,
  coalesce(c.manual_price, round(sum(p.factory_rate * i.quantity), 2)) as calculated_price,
  round(sum(p.factory_rate * i.quantity), 2) as live_items_total,
  sum(i.quantity)::integer as total_units,
  count(i.id)::integer as distinct_products,
  jsonb_agg(jsonb_build_object(
    'item_id', i.id,
    'product_id', p.id,
    'product_code', p.product_code,
    'name', p.name,
    'category', p.category,
    'pack_type', p.pack_type,
    'quantity', i.quantity,
    'unit_rate', p.factory_rate,
    'image_url', coalesce(p.image_url, p.product_image),
    'stock_status', p.stock_status,
    'item_label', i.item_label,
    'item_note', i.item_note
  ) order by i.display_order, i.id) as items
from public.combo_packs c
join public.combo_pack_items i on i.combo_id = c.id
join public.products p on p.id = i.product_id and p.is_active = true
where c.website_key = 'cart' and c.is_active = true
group by c.id;

alter view public.combo_pack_catalogue set (security_invoker = true);
grant select on public.combo_pack_catalogue to anon, authenticated;

-- The live database is already seeded by migration create_combo_master_and_detail_catalogue.
-- Keep this file as the canonical additive schema / API contract for the combo subsystem.
