-- RedThunder storefront: customer-focused homepage merchandising.
-- Additive only. Does not alter public.products, orders, cart, checkout, auth or RLS.
-- Website isolation: website_key is fixed to 'cart'.

create table if not exists public.homepage_customer_picks (
  id bigint generated by default as identity primary key,
  website_key text not null default 'cart',
  product_id uuid not null references public.products(id) on delete cascade,
  display_order integer not null default 0 check (display_order >= 0),
  is_active boolean not null default true,
  badge_text text,
  customer_label text,
  customer_reason text,
  customer_score numeric(5,2) check (customer_score is null or (customer_score >= 0 and customer_score <= 100)),
  rating_stars numeric(2,1) check (rating_stars is null or (rating_stars >= 0 and rating_stars <= 5)),
  rating_count integer not null default 0 check (rating_count >= 0),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (website_key, product_id),
  check (website_key = 'cart')
);

create index if not exists homepage_customer_picks_active_order_idx
  on public.homepage_customer_picks (website_key, is_active, display_order, id);

alter table public.homepage_customer_picks enable row level security;
revoke all on public.homepage_customer_picks from anon, authenticated;
grant select on public.homepage_customer_picks to anon, authenticated;
grant insert, update, delete on public.homepage_customer_picks to authenticated;

drop policy if exists homepage_customer_picks_public_read on public.homepage_customer_picks;
create policy homepage_customer_picks_public_read
  on public.homepage_customer_picks for select to anon, authenticated
  using (website_key = 'cart' and is_active = true);

drop policy if exists homepage_customer_picks_admin_write on public.homepage_customer_picks;
create policy homepage_customer_picks_admin_write
  on public.homepage_customer_picks for all to authenticated
  using ((select private.is_admin()) and website_key = 'cart')
  with check ((select private.is_admin()) and website_key = 'cart');

-- Optional starter merchandising rows. These reference existing products only.
-- rating_stars/rating_count intentionally start empty/zero because the current review table has no reviews.
insert into public.homepage_customer_picks
  (website_key, product_id, display_order, is_active, badge_text, customer_label, customer_reason, customer_score)
select 'cart', p.id, seed.display_order, true, seed.badge_text, seed.customer_label, seed.customer_reason, seed.customer_score
from public.products p
join (values
  (1,1,'Customer Pick','Starter Favourite','Easy entry-price celebration pick',99.0),
  (25,2,'Family Pick','Family Favourite','Classic fountain choice for family celebrations',98.0),
  (35,3,'Customer Pick','Ground Fun','A crowd-friendly spinning classic',97.0),
  (51,4,'Customer Pick','Rocket Pick','Aerial excitement at a practical price',96.0),
  (60,5,'Value Pick','Longer Show','Great-value fountain for bigger moments',95.0),
  (92,6,'Premium Pick','Premium Favourite','Premium fancy-variety choice',94.0),
  (112,7,'Kids Pick','Kids Favourite','Novelty-style pick for younger celebrations',93.0),
  (118,8,'Combo Pick','Starter Gift Box','Easy all-in-one assortment',92.0),
  (122,9,'Combo Pick','Family Gift Box','Balanced family celebration assortment',91.0),
  (126,10,'Premium Pick','Royal Celebration','Large-format premium assortment',90.0)
) as seed(product_code,display_order,badge_text,customer_label,customer_reason,customer_score)
  on p.product_code = seed.product_code
where p.is_active = true
on conflict (website_key, product_id) do update set
  display_order=excluded.display_order,
  is_active=excluded.is_active,
  badge_text=excluded.badge_text,
  customer_label=excluded.customer_label,
  customer_reason=excluded.customer_reason,
  customer_score=excluded.customer_score,
  updated_at=now();
