import React, { createContext, useContext, useEffect, useState, useCallback } from 'react';
import { Product } from '../data/products';
import { dbSelect } from '../lib/supabase';
export type DbProduct = Product & { dbId: string; skuCode?: string; factoryRate?: number; mrpRate?: number; availableQuantity?: number; isBestseller?: boolean; isFeatured?: boolean; isGreenCracker?: boolean };
interface ProductsContextType { products: DbProduct[]; isLoading: boolean; refreshProducts: () => Promise<void>; }
const ProductsContext=createContext<ProductsContextType|undefined>(undefined);
function mapProduct(row:any):DbProduct{return {id:Number(row.product_code),dbId:row.id,sNo:Number(row.s_no??row.product_code),name:row.name,category:row.category,unit:row.pack_type,rate:Number(row.factory_rate??row.rate??0),description:row.description||'',pieces:row.pieces_per_pack?String(row.pieces_per_pack):undefined,imageUrl:row.image_url||row.product_image||undefined,stockStatus:row.stock_status,popular:!!row.is_bestseller,featured:!!row.is_featured,factoryRate:Number(row.factory_rate??row.rate??0),mrpRate:Number(row.mrp_rate??row.rate??0),availableQuantity:Number(row.available_quantity??0),isBestseller:!!row.is_bestseller,isFeatured:!!row.is_featured,isGreenCracker:!!row.is_green_cracker};}
export const ProductsProvider:React.FC<{children:React.ReactNode}>=({children})=>{const[products,setProducts]=useState<DbProduct[]>([]);const[isLoading,setIsLoading]=useState(true);const refreshProducts=useCallback(async()=>{setIsLoading(true);try{const rows=await dbSelect<any>('products','select=*&is_active=eq.true&order=s_no.asc');setProducts(rows.map(mapProduct));}catch(e){console.error('Failed to load products from Supabase',e);setProducts([]);}finally{setIsLoading(false);}},[]);useEffect(()=>{refreshProducts();},[refreshProducts]);return <ProductsContext.Provider value={{products,isLoading,refreshProducts}}>{children}</ProductsContext.Provider>;};
export const useProducts=()=>{const c=useContext(ProductsContext);if(!c)throw new Error('useProducts must be used within ProductsProvider');return c;};
